//! Integration test that runs the detector over the pre-built test fixture WAV.
//!
//! The fixture is generated by the `make_test_wav` binary:
//!
//! ```shell
//! cargo run --bin make_test_wav
//! ```
//!
//! If the fixture does not exist, this test prints a skip notice and exits
//! successfully (so CI still passes without the dataset).

use guitar_pitch_detection::GuitarPitchDetector;
use std::path::Path;

// ── Constants ──────────────────────────────────────────────────────────────────

/// Maximum allowed fixture duration: 3 minutes + 1-second tolerance.
const MAX_FIXTURE_DURATION_SECONDS: f32 = 181.0;

// ── Helpers (mirrors decode_wav_i16 from dataset_tests.rs) ───────────────────

/// Decode a 16-bit PCM WAV byte slice into mono f32 samples.
///
/// Supports 8-bit and 16-bit PCM WAV files, mono and stereo (stereo is
/// downmixed by averaging channels).
///
/// # Returns
/// A tuple `(samples, sample_rate)` where `samples` is a `Vec<f32>` of mono
/// samples normalised to `[-1.0, 1.0]` and `sample_rate` is the audio sample
/// rate in Hz.  Returns `(vec![], 0)` when the data is invalid or empty.
fn decode_wav_i16(wav: &[u8]) -> (Vec<f32>, u32) {
    if wav.len() < 44 {
        return (vec![], 0);
    }
    let num_channels = u16::from_le_bytes([wav[22], wav[23]]) as usize;
    let sample_rate = u32::from_le_bytes([wav[24], wav[25], wav[26], wav[27]]);
    let bits_per_sample = u16::from_le_bytes([wav[34], wav[35]]) as usize;

    // Find "data" chunk.
    let mut pos = 12usize;
    let data_start;
    let data_len;
    loop {
        if pos + 8 > wav.len() {
            return (vec![], sample_rate);
        }
        let chunk_id = &wav[pos..pos + 4];
        let chunk_size =
            u32::from_le_bytes([wav[pos + 4], wav[pos + 5], wav[pos + 6], wav[pos + 7]]) as usize;
        if chunk_id == b"data" {
            data_start = pos + 8;
            data_len = chunk_size;
            break;
        }
        pos += 8 + chunk_size;
    }

    let data = &wav[data_start..(data_start + data_len).min(wav.len())];
    let bytes_per_sample = bits_per_sample / 8;
    let frame_bytes = bytes_per_sample * num_channels;

    if frame_bytes == 0 {
        return (vec![], sample_rate);
    }

    let mut samples = Vec::with_capacity(data.len() / frame_bytes);
    let mut i = 0;
    while i + frame_bytes <= data.len() {
        let mut sum = 0.0f32;
        for ch in 0..num_channels {
            let off = i + ch * bytes_per_sample;
            let s = match bits_per_sample {
                16 => i16::from_le_bytes([data[off], data[off + 1]]) as f32 / 32_768.0,
                8 => (data[off] as f32 - 128.0) / 128.0,
                _ => 0.0,
            };
            sum += s;
        }
        samples.push(sum / num_channels as f32);
        i += frame_bytes;
    }
    (samples, sample_rate)
}

// ── Tests ─────────────────────────────────────────────────────────────────────

/// Run the detector over every frame of the test-fixture WAV and assert that
/// at least one note is detected somewhere in the file.
#[test]
fn fixture_wav_detects_notes() {
    let fixture = Path::new("tests/dataset/test_fixture.wav");

    if !fixture.exists() {
        println!(
            "[SKIP] test_fixture.wav not found at {}.\n\
             Run `cargo run --bin make_test_wav` to generate it.",
            fixture.display()
        );
        return;
    }

    let bytes = std::fs::read(fixture).expect("failed to read test_fixture.wav");
    let (samples, sample_rate) = decode_wav_i16(&bytes);

    assert!(!samples.is_empty(), "test_fixture.wav contained no samples");

    let sr = if sample_rate == 0 { 44_100 } else { sample_rate };
    let frame_size = 512usize;
    let mut detector = GuitarPitchDetector::new(sr, frame_size);

    let mut total_frames = 0usize;
    let mut frames_with_notes = 0usize;
    let mut first_note: Option<String> = None;

    for chunk in samples.chunks(frame_size) {
        let result = detector.process(chunk);
        total_frames += 1;

        if !result.notes.is_empty() {
            frames_with_notes += 1;
            if first_note.is_none() {
                let n = &result.notes[0];
                first_note = Some(format!(
                    "{} ({:.1} Hz, confidence {:.2})",
                    n.name, n.frequency, n.confidence
                ));
            }
        }
    }

    println!(
        "test_fixture.wav: {} frames total, {} frames with notes ({:.1}%)",
        total_frames,
        frames_with_notes,
        100.0 * frames_with_notes as f32 / total_frames.max(1) as f32
    );
    if let Some(note) = &first_note {
        println!("First detected note: {}", note);
    }

    assert!(
        frames_with_notes > 0,
        "No notes detected anywhere in test_fixture.wav"
    );
}

/// Verify the fixture WAV has a plausible duration (between 1 s and 3 min).
#[test]
fn fixture_wav_duration_is_valid() {
    let fixture = Path::new("tests/dataset/test_fixture.wav");

    if !fixture.exists() {
        println!("[SKIP] test_fixture.wav not found — skipping duration check.");
        return;
    }

    let bytes = std::fs::read(fixture).expect("failed to read test_fixture.wav");
    let (samples, sample_rate) = decode_wav_i16(&bytes);

    let sr = if sample_rate == 0 { 44_100 } else { sample_rate };
    let duration_s = samples.len() as f32 / sr as f32;

    println!(
        "test_fixture.wav: {:.1} s ({:.1} min) at {} Hz",
        duration_s,
        duration_s / 60.0,
        sr
    );

    assert!(duration_s >= 1.0, "Fixture is shorter than 1 second");
    assert!(
        duration_s <= MAX_FIXTURE_DURATION_SECONDS,
        "Fixture is longer than 3 minutes ({:.1} s)",
        duration_s
    );
}
