//! Integration test that runs the detector over the pre-built test fixture WAV.
//!
//! The fixture is generated by the `make_test_wav` binary:
//!
//! ```shell
//! cargo run --bin make_test_wav
//! ```
//!
//! If the fixture does not exist, this test prints a skip notice and exits
//! successfully (so CI still passes without the dataset).
//!
//! All tests print a structured line per check:
//! `[  N ms] Expected: <X>  |  Detected: <Y>  –  OK / FAILED`

use guitar_pitch_detection::GuitarPitchDetector;
use std::path::Path;

// ── Constants ──────────────────────────────────────────────────────────────────

/// Maximum allowed fixture duration: 3 minutes + 1-second tolerance.
const MAX_FIXTURE_DURATION_SECONDS: f32 = 181.0;

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Decode a 16-bit PCM WAV byte slice into mono f32 samples.
///
/// Supports 8-bit and 16-bit PCM WAV files, mono and stereo (stereo is
/// downmixed by averaging channels).
///
/// # Returns
/// A tuple `(samples, sample_rate)` where `samples` is a `Vec<f32>` of mono
/// samples normalised to `[-1.0, 1.0]` and `sample_rate` is the audio sample
/// rate in Hz.  Returns `(vec![], 0)` when the data is invalid or empty.
fn decode_wav_i16(wav: &[u8]) -> (Vec<f32>, u32) {
    if wav.len() < 44 {
        return (vec![], 0);
    }
    let num_channels = u16::from_le_bytes([wav[22], wav[23]]) as usize;
    let sample_rate = u32::from_le_bytes([wav[24], wav[25], wav[26], wav[27]]);
    let bits_per_sample = u16::from_le_bytes([wav[34], wav[35]]) as usize;

    // Find "data" chunk.
    let mut pos = 12usize;
    let data_start;
    let data_len;
    loop {
        if pos + 8 > wav.len() {
            return (vec![], sample_rate);
        }
        let chunk_id = &wav[pos..pos + 4];
        let chunk_size =
            u32::from_le_bytes([wav[pos + 4], wav[pos + 5], wav[pos + 6], wav[pos + 7]]) as usize;
        if chunk_id == b"data" {
            data_start = pos + 8;
            data_len = chunk_size;
            break;
        }
        pos += 8 + chunk_size;
    }

    let data = &wav[data_start..(data_start + data_len).min(wav.len())];
    let bytes_per_sample = bits_per_sample / 8;
    let frame_bytes = bytes_per_sample * num_channels;

    if frame_bytes == 0 {
        return (vec![], sample_rate);
    }

    let mut samples = Vec::with_capacity(data.len() / frame_bytes);
    let mut i = 0;
    while i + frame_bytes <= data.len() {
        let mut sum = 0.0f32;
        for ch in 0..num_channels {
            let off = i + ch * bytes_per_sample;
            let s = match bits_per_sample {
                16 => i16::from_le_bytes([data[off], data[off + 1]]) as f32 / 32_768.0,
                8 => (data[off] as f32 - 128.0) / 128.0,
                _ => 0.0,
            };
            sum += s;
        }
        samples.push(sum / num_channels as f32);
        i += frame_bytes;
    }
    (samples, sample_rate)
}

/// Print one verbose check line.
///
/// ```text
/// [180000.0 ms] Expected: ≥1 note detected in fixture  |  Detected: E2 at 11.6 ms  –  OK
/// ```
fn check(time_ms: f32, expected: &str, detected: &str, passed: bool) {
    println!(
        "[{:9.1} ms] Expected: {:<50}  |  Detected: {}  –  {}",
        time_ms,
        expected,
        detected,
        if passed { "OK" } else { "FAILED" }
    );
}

// ── Tests ─────────────────────────────────────────────────────────────────────

/// Run the detector over every frame of the test-fixture WAV and assert that
/// at least one note is detected somewhere in the file.
#[test]
fn fixture_wav_detects_notes() {
    let fixture = Path::new("tests/dataset/test_fixture.wav");

    if !fixture.exists() {
        println!(
            "[SKIP] test_fixture.wav not found at {}.\n\
             Run `cargo run --bin make_test_wav` to generate it.",
            fixture.display()
        );
        return;
    }

    let bytes = std::fs::read(fixture).expect("failed to read test_fixture.wav");
    let (samples, sample_rate) = decode_wav_i16(&bytes);

    assert!(!samples.is_empty(), "test_fixture.wav contained no samples");

    let sr = if sample_rate == 0 { 44_100 } else { sample_rate };
    let frame_size = 512usize;
    let mut detector = GuitarPitchDetector::new(sr, frame_size);

    let mut total_frames = 0usize;
    let mut frames_with_notes = 0usize;
    let mut first_note_ms: Option<f32> = None;
    let mut first_note_str = String::new();

    for (frame_idx, chunk) in samples.chunks(frame_size).enumerate() {
        let frame_ms = frame_idx as f32 * frame_size as f32 * 1_000.0 / sr as f32;
        let result = detector.process(chunk);
        total_frames += 1;

        if !result.notes.is_empty() {
            frames_with_notes += 1;
            if first_note_ms.is_none() {
                let n = &result.notes[0];
                first_note_ms = Some(frame_ms);
                first_note_str = format!(
                    "{} (MIDI {}, {:.1} Hz, conf {:.2})",
                    n.name, n.midi_note, n.frequency, n.confidence
                );
            }
        }
    }

    let total_ms = samples.len() as f32 * 1_000.0 / sr as f32;
    let det_ratio = 100.0 * frames_with_notes as f32 / total_frames.max(1) as f32;

    // Print summary stats
    println!(
        "\ntest_fixture.wav: {} frames total, {} frames with notes ({:.1}%)",
        total_frames, frames_with_notes, det_ratio
    );

    // Verbose check: first note detection
    let det_str = match first_note_ms {
        Some(t) => format!("{} at {:.1} ms", first_note_str, t),
        None    => "(no notes anywhere in fixture)".to_string(),
    };
    check(
        total_ms,
        "≥1 note detected somewhere in test_fixture.wav",
        &det_str,
        frames_with_notes > 0,
    );

    // Verbose check: detection rate
    check(
        total_ms,
        "Detection rate > 0%",
        &format!("{:.1}% of frames contain notes", det_ratio),
        frames_with_notes > 0,
    );

    assert!(
        frames_with_notes > 0,
        "No notes detected anywhere in test_fixture.wav"
    );
}

/// Verify the fixture WAV has a plausible duration (between 1 s and 3 min).
#[test]
fn fixture_wav_duration_is_valid() {
    let fixture = Path::new("tests/dataset/test_fixture.wav");

    if !fixture.exists() {
        println!("[SKIP] test_fixture.wav not found — skipping duration check.");
        return;
    }

    let bytes = std::fs::read(fixture).expect("failed to read test_fixture.wav");
    let (samples, sample_rate) = decode_wav_i16(&bytes);

    let sr = if sample_rate == 0 { 44_100 } else { sample_rate };
    let duration_s = samples.len() as f32 / sr as f32;
    let duration_ms = duration_s * 1_000.0;

    let det_str = format!("{:.1} s ({:.1} min) at {} Hz", duration_s, duration_s / 60.0, sr);

    // Lower bound: at least 1 second
    let min_ok = duration_s >= 1.0;
    check(
        duration_ms,
        "Duration ≥ 1.0 s",
        &det_str,
        min_ok,
    );
    assert!(min_ok, "Fixture is shorter than 1 second");

    // Upper bound: at most 3 minutes + 1 s tolerance
    let max_ok = duration_s <= MAX_FIXTURE_DURATION_SECONDS;
    check(
        duration_ms,
        &format!("Duration ≤ {:.0} s (3 min + 1 s tolerance)", MAX_FIXTURE_DURATION_SECONDS),
        &det_str,
        max_ok,
    );
    assert!(
        max_ok,
        "Fixture is longer than 3 minutes ({:.1} s)",
        duration_s
    );
}
